### ISSUE TITLE
configOverwrite ignored if the first argument doesn't have the correct object keys

### ISSUE THREAD

**Issue by dandv** [juliancwirko/meteor-s-alert#29]
```js
Collection.remove(someId, function (error) {
  sAlert.error(error, {effect: 'slide', position: 'top-right', timeout: 3000});
});
```

Without  `error.toString()`, the effect, position and timeout won't be applied. If passed an object as the first argument, sAlert expects [custom fields](https://github.com/juliancwirko/meteor-s-alert#custom-fields), but only the `message` key matches. Presumably not finding the other fields throws it off.

**Comment by juliancwirko** [comment]
Ok, I will look into it tomorrow. Thanks.

**Comment by juliancwirko** [comment]
Hey, I have done some tests and it seems it is not working because `error` isn't a standard Object. This is a js error object and it will not work here. When you call toString() on it it will only return error message which is a string. 

sAlert will work with something like:

```handlebars
<body>
    {{> sAlert template="sss"}}
</body>

<template name="sss">
    <div class="custom-alert-class s-alert-box s-alert-{{condition}} s-alert-{{position}} s-alert-effect-{{effect}} s-alert-show" id="{{_id}}" style="{{boxPosition}}">
        <div class="s-alert-box-inner">
            <div>error: {{error}}</div>
            <div>reason: {{reason}}</div>
            <div>message: {{message}}</div>
            <div>errorType: {{errorType}}</div>
        </div>
        <span class="s-alert-close"></span>
    </div>
</template>
```
and

```javascript
Collection.remove(someId, function (error) {
  sAlert.error({error: 404, reason: "Error 404: Not found", details: "", message: "Error 404: Not found [404]", errorType: "Meteor.Error"}, {effect: 'slide', position: 'top-right', timeout: 3000});
});
```

This is exactly what `error` object has, but it is not a standard Object type, so everything seems to work ok, but you need to parse it like `JSON.parse(JSON.stringify(error))`

I have added it in the s-Alert core. It shouldn't break anything. It will parse js error object and it will not break proper standard objects.

Anyway, now with a standard template when you pass meteor error object it should get message and display it. When you use custom template you could display other meteor error informations like in the example above.

Let me know if this helps. Thanks.

**Comment by dandv** [comment]
Thanks for looking into this. Instead of `JSON.parse(JSON.stringify(error))` I had used error.toString(), but perhaps your code is more robust if `error` somehow doesn't have a `toString()` method, though it does depend on the object having a `message` field, no?

**Comment by juliancwirko** [comment]
`error` should have `toString()` but then it will return only one string, and you will be not able to get other fields from error object . I tought that sometimes we might want to have it in custom sAlert templates like in the example above. Anyway, it should now work with `error.toString()` and `error`.

**Comment by juliancwirko** [comment]
I close this for now...
