### ISSUE TITLE
Server collection

### ISSUE THREAD

**Issue by Maksim09** [juliancwirko/meteor-s-alert#36]
Someone has an idea how to observe/subscribe server collections and display messages based on this collection without a pull client collection to server collection

**Comment by juliancwirko** [comment]
Hi, I don't know if I understand it correctly.. you want to observe server only collection? 

I think that you need something on the client side anyway. 
sAlert works only on client side and it uses client side only collection. In most cases it is enough because you can catch Meteor.call(...) callbacks on the client and you can observe client-server based collections. I think you probably want to have some part of this collection on the client too if you want to notify your users.

**Comment by Maksim09** [comment]
Thank you for quick response.
I want to display alert for all users when collection exist in mongodb.
I try to use collection.observeChanges({ added: function (id, fields) { run Function(); }
but this works only when collection changes.

**Comment by juliancwirko** [comment]
I think you could have client collection too with fields narrowed to only '_id' and then check if it exists. But I don't know exactly when you want to check this. You could check it on Meteor.startup, on user login or even on some template rendered event.

If you don't want to share the collecton on the client side you could make Meteor.call(...) on the client and catch callbacks to check if the collection exists.

Maybe someone will have better ideas...

**Comment by juliancwirko** [comment]
Hey, for now I don't plan any server side work in this package. I close this issue for now. If you have more questions you can still comment here. Thanks.
