### ISSUE TITLE
Close on second route change

### ISSUE THREAD

**Issue by TechplexEngineer** [juliancwirko/meteor-s-alert#39]
Is there a way to close an alert after the second route change?

My use case is showing a success alert after successfully inserting into the database from a from, then redirecting the user to the view that shows their newly inserted record. I'd like to show a success message on the list page.

**Comment by juliancwirko** [comment]
Hi, this is a very custom use case. I think you could disable onRouteClose by config `onRouteClose: false` and then on your view 'newly inserted record' on some router hook (triggersExit - FlowRouter, onStop - Iron Router) you could clear alerts by calling `sAlert.closeAll()`

I don't plan such logic because it could be done per project and it will be to much routing logic in the package.

**Comment by juliancwirko** [comment]
I close it for now. If you have more questions you can still comment here.
