### ISSUE TITLE
Could this work with angular meteor?

### ISSUE THREAD

**Issue by dragonfire1119** [juliancwirko/meteor-s-alert#42]
I know this is built for meteor but I'm currently using the angular meteor right now. You did a integration with react but I was wondering if you had a plan on angular meteor? Thanks for your time and work on this project.

**Comment by juliancwirko** [comment]
Hi, there isn't an integration with React. There is only a way to use it with React. You might (probably) do the same with angular. But I don't use Angular. You need to use Blaze and Angular in one app. You just need to include sAlert template in the body (or main layout) and then you can use global sAlert methods in you Angular code.

**Comment by dragonfire1119** [comment]
@juliancwirko Thanks for the reply. I been trying to figure out react on uploading images the only reason I'm using angular is because I like https://github.com/danialfarid/ng-file-upload. But I'm missing sAlert LOL. I thought this https://github.com/Urigo/angular-blaze-template might work but I keep geting ``ReferenceError: Template is not defined``

**Comment by juliancwirko** [comment]
Hmmm, hard to say because I haven't create any (even simple) Meteor-Angular app. Is it possible to just place something like:

```
<body>
    {{> sAlert}}
</body>
```

somewhere on the 'client' side? I suspect not ;) because of ` meteor remove blaze-html-templates` 

So, maybe you will be able to clone the sAlert repo into your `/packages` folder and then modify package to use `angular-blaze-template`. The error is probably because the sAlert package should load before `angular-blaze-template`.

You might also try to do the oposite and clone `angular-blaze-template` code into your app. This is only one file on the client side: https://github.com/Urigo/angular-blaze-template/blob/master/angular-blaze-template.js and then the sAlert template should be ready for it. 

I am just guesing without testing it :/

**Comment by dragonfire1119** [comment]
@juliancwirko I think I figured it out I used https://atmospherejs.com/meteor/angular-with-blaze & include ng-file-upload. I didn't remove blaze so I can still use sAlert.

**Comment by juliancwirko** [comment]
:+1: :)

**Comment by dragonfire1119** [comment]
I can also use react so I get the best of both worlds without having to use all of angular. I appreciate you helping me out :+1:
